export const GYM_LIST_REQUEST = "GYM_LIST_REQUEST",
  GYM_LIST_SUCCESS = "GYM_LIST_SUCCESS",
  GYM_API_BASEURL = "http://localhost:5000/api/v1/gyms",
  GYM_LIST_ERROR = "GYM_LIST_ERROR",
  CREATE_GYM = "CREATE_GYM";
