export const LOGOUT_REQUEST = "",
  LOGIN_SUCCESS = "LOGIN_REQUEST",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_ERROR = " LOGIN_ERROR ",
  LOGOUT_ERROR = "LOGOUT_ERROR",
  USER_API_BASEURL = "http://localhost:5000/api/v1/users";
